// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsbtweisyvebbxwmjqst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzYnR3ZWlzeXZlYmJ4d21qcXN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNzQyMzAsImV4cCI6MjA2MDc1MDIzMH0.BLX38sg7hHDGmhdK-qiuFP_VKVYmpkD1POFX-1owKLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);